#!bin/bash
set -x

#########
#This code will check if you have an IMP and Runplan for your current settings. 
#Then run exteranls on all parts of your target.
################################
home=${PWD}

if [ $# -lt 2 ]
then
	echo "Please enter the target you would like to use...(He3, H3, D2)"
	read tgt
	echo "Please enter the ANGLE you want to look at, or k for kin. number"
	read angle
	if [ "${angle}" == "k" ]
	then
		echo "Kin :"
		read kin
	fi
	
else
	tgt=$1
	angle=$2
	if [ "${angle}" == "k" ]
	then
		kin=$3
	fi
fi
E=-1		
while IFS=, read kinin Ein Epin thetain
do
	if [ "${kinin}" ==  "${kin}" ]
	then
		E=$Ein
		Ep=$Epin
		theta=$thetain
		break
	fi
done < marathon_kin_table.csv

if [ "${E}" == "-1" ]
then
	echo "Missing kin info"
	exit
fi



File=RUNPLAN/marathon_kin${kin}.inp
if [ -e RUNPLAN/marathon_kin${kin}.inp ]
then
	FileS=$(stat -c%s ${File})
else
	FileS=0
fi

if [ -e "${File}" ] &&  [ "${FileS}" -gt 1000 ]
then
	a=a
else
	echo "Making RUNPLAN"
	cd RUNPLAN	
	root -b -l -q "gen_Runplan.C(0,${E},${Ep},${theta},\"kin${kin}\",0)"
	cd $home
fi

if [ "$tgt" == "D2" ]
then
        echo "D2"
        tarid=2
elif [ "$tgt" == "H3" ]
then
        echo "H3"
        tarid=3

elif [ "$tgt" == "He3" ]
then
        echo "He3"
        tarid=4
elif [ "$tgt" == "C12" ]
then
        echo "C12"
        tarid=7
else
        echo "dummy"
        tarid=0
fi



suffix[1]=""
suffix[2]=""
suffix[3]=""
suffix[4]=""
suffix[5]="_Alwalls_Up"
suffix[6]="_Alwalls_Dn"
suffix[7]=""

target=$tgt

if [[ ${tarid} -lt 5 ]]
then
	cd "INP"
	i=1
	for x in $tarid 5 6
	do
		target="${tgt}${suffix[${x}]}"
		sh gen_inp $kin $target
	done
	cd $home
	echo "Starting the table generation"
	echo "This will take a while"
	sh gen_target_complete  marathon_kin${kin}_${tgt}  ${kin}  ${tgt}  ${tarid}
else
	cd "INP"
	sh gen_inp $kin $target
	cd $home
	echo "Starting the table generation"
	echo "This will take a while"
	sh gen_table  marathon_kin${kin}_${target}  ${kin}  ${tgt}  ${tarid}
fi
