#!bin/bash
set -x

#########
#This code will check if you have an IMP and Runplan for your current settings. 
#Then run exteranls on all parts of your target.
################################
home=${PWD}

if [ $# -lt 2 ]
then
	echo "Please enter the target you would like to use...(He3, H3, D2)"
	read tgt
	echo "Please enter the kin number"
	read  kin
	echo "Please enter tgt id"
	read tarid
else
	tgt=$1
	kin=$2
	tarid=$3
fi
E=-1		
while IFS=, read kinin Ein Epin thetain
do
	if [ "${kinin}" ==  "${kin}" ]
	then
		E=$Ein
		Ep=$Epin
		theta=$thetain
		break
	fi
done < marathon_kin_table.csv

if [ "${E}" == "-1" ]
then
	echo "Missing kin info"
	exit
fi



File=RUNPLAN/marathon_kin${kin}.inp
if [ -e RUNPLAN/marathon_kin${kin}.inp ]
then
	FileS=$(stat -c%s ${File})
else
	FileS=0
fi

if [ -e "${File}" ] &&  [ "${FileS}" -gt 1000 ]
then
	a=a
else
	echo "Making RUNPLAN"
	cd RUNPLAN	
	root -b -l -q "gen_Runplan.C(0,${E},${Ep},${theta},\"kin${kin}\",0)"
	cd $home
fi

suffix[1]=""
suffix[2]=""
suffix[3]=""
suffix[4]="_Alwalls_Up"
suffix[5]="_Alwalls_Dn"

cd "INP"

target="${tgt}${suffix[${tgtid}]}"
sh gen_inp ${kin} ${target}
cd $home
echo "Starting the table generation"
echo "This will take a while"
sh gen_table  marathon_kin${kin}_${target}  ${kin}  ${tgt}  ${tarid}


