#!bin/bash
#set -x
if [ $# -lt 4 ]
then
	echo "Please enter the INP file for the simulation"
	read INP
	echo "Please enter the kin # for this table"
	read kin 
	echo "Please enter tgt name: He3,H3,D2..."
	read tgt
	echo "Please enter tgt id: D2=2, H3=3, He3 =4, entrance wall=5, exit wall =6, single foil =7"
	read ID
else
	INP=$1
	kin=$2
	tgt=$3
	ID=$4
fi

if [ -e OUT/${INP}.out ]
then
#	echo "Table already exist would you like to gen again, (y/n)"
#	read check
	if [ "${check}" != "y" ]
	then
		exit
	fi
fi
now=$(date +"%T")
echo "Current time : $now"

./externals_all << endofinput > runout/${INP}.out
${INP}
endofinput

if [ -e OUT/table_${INP}.out ]
then
	rm -v OUT/table_${INP}.out
fi
./rc_convert ${INP}.out

mv OUT/table_${INP}.out OUT/kin${kin}_${tgt}_${ID}.out

now=$(date +"%T")
echo "Current time : $now"



