#!bin/bash
#set -x


if [ $# -lt 4 ]
then
        echo "Please enter the INP file for the simulation"
        read INP
        echo "Please enter the kin number for this table"
        read kin 
        echo "Please enter tgt name: He3,H3,D2..."
        read tgt
        echo "Please enter tgt id: D2=2, H3=3, He3 =4 single foil =7"
        read ID
else
        INP=$1
        kin=$2
        tgt=$3
        ID=$4
fi

if [ ID == 7 ] #Still need to work on foil
then
	exit
fi

suffx[1]=""
suffx[2]=""
suffx[3]=""
suffx[4444]=""
suffx[5]=_Alwalls_Up
suffx[6]=_Alwalls_Dn 
i=1
INP1=$INP
for x in $ID 5 6 
	do
	INP1="${INP}${suffx[${x}]}"
	sh gen_table ${INP1} ${kin} ${tgt} ${x}


done
