#!bin/bash
#set -x


if [ $# -lt 4 ]
then
        echo "Please enter the INP file for the simulation"
        read INP
        echo "Please enter the run number this for"
        read runnum
        echo "Please enter tgt name: He3,H3,D2..."
        read tgt
        echo "Please enter tgt id: D2=1, H3=2, He3 =3 single foil =6"
        read ID
else
        INP=$1
        runnum=$2
        tgt=$3
        ID=$4
fi

if [ ID == 6 ]
then
	exit
fi

suffx[1]=""
suffx[2]=""
suffx[3]=""
suffx[4]=_Alwalls_Up
suffx[5]=_Alwalls_Dn 
i=1
INP1=$INP
for x in $ID 4 5
	do
	INP1="${INP}${suffx[${x}]}"
	sh gen_table ${INP1} ${runnum} ${tgt} ${x}


done
