#!bin/bash
set -x
if [ $# -lt 4 ]
then
	echo "Please enter the INP file for the simulation"
	read INP
	echo "Please enter the run number this for"
	read runnum
	echo "Please enter tgt name: He3,H3,D2..."
	read tgt
	echo "Please enter tgt id: D2=1, H3=2, He3 =3, entrance wall=4, exit wall =5, single foil =6"
	read ID
else
	INP=$1
	runnum=$2
	tgt=$3
	ID=$4
fi

if [ -e OUT/${INP}.out ]
then
	echo "Table already exist would you like to gen again, (y/n)"
	read check
	if [ "${check}" != "y" ]
	then
		exit
	fi
fi

./externals_all << endofinput > runout/${INP}.out
${INP}
endofinput

if [ -e OUT/table_${INP}.out ]
then
	rm -v OUT/table_${INP}.out
fi
./rc_convert ${INP}.out

mv OUT/table_${INP}.out OUT/${tgt}_${runnum}_${ID}.out





